name: covid
description: Info Covid-19

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  youtube_player_flutter: ^6.1.0+7
  flutter:
    sdk: flutter
  
  # Internalization
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  intl: 0.16.0

  # Services
  dio: 3.0.9
  logger: 0.8.3
  url_launcher: ^5.4.5
  notification_permissions: 0.4.4
  app_settings: ^4.0.0

  # App
  cupertino_icons: 0.1.3
  provider: 4.0.5
  rxdart: 0.24.0
  html: 0.14.0+3
  flutter_html: 0.11.1


  # Firebase
  firebase_core: 0.4.4+3
  # For the FlutterFire plugin for Google Analytics
  firebase_analytics: 5.0.11
  # Firebase Crashlytics  
  firebase_crashlytics: 0.1.3+3
  # Firebase Messaging 
  firebase_messaging: 6.0.13

  # UI
  google_fonts: 0.6.2
  flare_flutter: 2.0.3

  # Svg
  flutter_svg: ^0.17.4

  # Icon Launcher
  flutter_launcher_icons: ^0.7.4

  # Expandable Tile
  expandable: ^4.1.3

  # Animation
  simple_animations: ^1.3.12

  # PDF
  flutter_full_pdf_viewer: ^1.0.6

  # Package Info
  package_info: ^0.4.0+17

  # Pull ro Refresh
  pull_to_refresh: ^1.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: 4.1.1
  build_runner: 1.8.1
  json_serializable: 3.3.0
  built_value_generator: ^7.0.9

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/icons/

flutter_intl:
  enabled: true

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/icons/icon.png"